setClass('myDate')
setAs("character","myDate", function(from) as.Date(from, format="%d/%m/%Y") )
data <- subset(read.csv("./household_power_consumption.txt", sep = ";", na.strings="?", colClasses = c("Date" = "myDate")), Date >= "2007/02/01" & Date <= "2007/02/02")
png(filename = "plot2.png", width = 480, height = 480, units = "px", bg ="transparent")
datetime <- as.POSIXct(paste(data$Date, data$Time), format = "%Y-%m-%d %H:%M:%S")
with(data, plot(datetime, Global_active_power, ylab = "Global Active Power (kilowatts)", xlab = "", type = "l"))
dev.off()